name: Pull Request

on: 
  pull_request:
    branches:
      - dev

jobs:
  static-analysis:
    runs-on: macos-latest
    outputs:
      libs: ${{ steps.danger.outputs.libs }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 100
      - name: Install Dependencies
        run: |
          npm install shelljs@0.8.5
          ./install.sh
      - name: Static Analysis and Danger
        if: ${{ github.event_name == 'pull_request' }} && (success() || failure())
        id: danger
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          xcodebuild analyze -workspace SalesforceMobileSDK.xcworkspace -scheme MobileSync -sdk 'iphonesimulator' \
            CLANG_ANALYZER_OUTPUT=plist-html CLANG_ANALYZER_OUTPUT_DIR=./clangReport RUN_CLANG_STATIC_ANALYZER=YES | xcbeautify
          cd .github
          bundle update && bundle install
          bundle exec danger --dangerfile=DangerStaticAnalysis.rb

  ios-pr:
    needs: [static-analysis]
    strategy:
      fail-fast: false
      matrix:
        lib: ${{ fromJson(needs.static-analysis.outputs.libs) }}
    uses: ./.github/workflows/reusable-workflow.yaml
    with:
      lib: ${{ matrix.lib }}