name: Pull Request

on:
  # Dangerious without Member Check setep! 
  pull_request_target:
    branches:
      - dev
  workflow_dispatch: "true"
    

jobs:
  static-analysis:
    runs-on: macos-15
    steps:
      - name: Member Check
        uses: octokit/request-action@v2.x
        id: member_check
        with:
          route: >
            GET /repos/${{ github.repository }}/collaborators/${{ github.triggering_actor }}/permission
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        - name: Validate Permissions
        run: |
          permissions=$(echo "${{ steps.member_check.outputs.data }}" | jq -r '.permission')
          echo "Triggering actor: \
            ${{ github.triggering_actor }} has permissions: $permissions"
          if [[ "$permissions" != "write" && "$permissions" != "admin" ]]; then
            echo "Pull Request not triggered by a user with sufficient permissions."
            echo "Someone from the team needs to rerun this workflow AFTER it has been deemed safe."
            exit 1
          fi
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # We need a sufficient depth or Danger will occasionally run into issues checking which files were modified.
          fetch-depth: 100
          # This is dangerous without the member check
          ref: ${{ github.event.pull_request.head.sha }} 
      - name: Install Dependencies
        run: |
          npm install shelljs@0.8.5
          ./install.sh
      - name: Run Static Analysis
        # It would be nice to use xcbeaufity here but all the warnings and errors get annotated onto the PR, including 
        # files not mofified in the PR which is annoying.  
        run: xcodebuild analyze -workspace SalesforceMobileSDK.xcworkspace -scheme MobileSync -sdk 'iphonesimulator' \
            CLANG_ANALYZER_OUTPUT=plist-html CLANG_ANALYZER_OUTPUT_DIR=./clangReport RUN_CLANG_STATIC_ANALYZER=YES
      - name: Report Static Analysis
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd .github/DangerFiles
          bundle update && bundle install
          bundle exec danger --dangerfile=StaticAnalysis.rb --danger_id=StaticAnalysis

  test-orchestrator:
    runs-on: macos-15
    outputs:
      libs: ${{ steps.test-orchestrator.outputs.libs }}
    steps:
      - name: Member Check
        uses: octokit/request-action@v2.x
        id: member_check
        with:
          route: >
            GET /repos/${{ github.repository }}/collaborators/${{ github.triggering_actor }}/permission
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Validate Permissions
        run: |
          permissions=$(echo "${{ steps.member_check.outputs.data }}" | jq -r '.permission')
          echo "Triggering actor: \
            ${{ github.triggering_actor }} has permissions: $permissions"
          if [[ "$permissions" != "write" && "$permissions" != "admin" ]]; then
            echo "Pull Request not triggered by a user with sufficient permissions."
            echo "Someone from the team needs to rerun this workflow AFTER it has been deemed safe."
            exit 1
          fi
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # We need a sufficient depth or Danger will occasionally run into issues checking which files were modified.
          fetch-depth: 100
          # This is dangerous without the member check
          ref: ${{ github.event.pull_request.head.sha }} 
      - name: Determine Tests to Run
        id: test-orchestrator
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd .github/DangerFiles
          bundle update && bundle install
          bundle exec danger --dangerfile=TestOrchestrator.rb

  ios-pr:
    needs: [test-orchestrator]
    strategy:
      fail-fast: false
      matrix:
        lib: ${{ fromJson(needs.test-orchestrator.outputs.libs) }}
    uses: ./.github/workflows/reusable-workflow.yaml
    with:
      lib: ${{ matrix.lib }}
    secrets: inherit
