on:
  workflow_dispatch:
  workflow_call:
    inputs:
      lib:
        required: true
        type: string
      ios:
        default: '^18'
        required: false
        type: string
      xcode:
        default: '^16'
        required: false
        type: string

jobs:
  test-ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        # We need a sufficient depth or Danger will occasionally run into issues 
        # checking which files were modified.
        with:
          fetch-depth: 100
      - name: Install Dependencies
        env: 
          TEST_CREDENTIALS: ${{ secrets.TEST_CREDENTIALS }}
        run: |
          npm install shelljs@0.8.5
          ./install.sh
          echo $TEST_CREDENTIALS > ./shared/test/test_credentials.json
      - uses: mxcl/xcodebuild@v3
        with:
          xcode: ${{ inputs.xcode }}
          platform: iOS
          platform-version: ${{ inputs.ios }}
          workspace: SalesforceMobileSDK.xcworkspace
          scheme: ${{ inputs.lib }}
          code-coverage: true
          upload-logs: always
      - name: Danger Test Results
        if: (github.event_name == 'pull_request') && failure()
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd .github/DangerFiles
          bundle update && bundle install
          bundle exec danger --dangerfile=TestResults.rb --danger_id=${{ inputs.lib }}
      - uses: codecov/codecov-action@v4
        with:
          flags: ${{ inputs.lib }}
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        if: success() || failure()