on:
  workflow_call:
    inputs:
      lib:
        required: true
        type: string
      ios:
        default: '^18'
        required: false
        type: string
      xcode:
        default: '^16'
        required: false
        type: string

jobs:
  test-ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 100
      - name: Install Dependencies
        run: |
          npm install shelljs@0.8.5
          ./install.sh
          echo ${{ secrets.TEST_CREDENTIALS }} > ./shared/test/test_credentials.json
      - uses: mxcl/xcodebuild@v3
        with:
          xcode: ${{ inputs.xcode }}
          platform: iOS
          platform-version: ${{ inputs.ios }}
          workspace: SalesforceMobileSDK.xcworkspace
          scheme: ${{ inputs.lib }}
          code-coverage: ${{ github.event_name == 'pull_request' }}
          upload-logs: always
      - name: Danger Test Results
        if: ${{ github.event_name == 'pull_request' }} && (success() || failure())
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd .github
          bundle update && bundle install
          bundle exec danger --dangerfile=DangerTestResults.rb --danger_id=${{ inputs.lib }}