on:
  workflow_call:
    inputs:
      lib:
        required: true
        type: string
      ios:
        default: '^18'
        required: false
        type: string
      xcode:
        default: '^16'
        required: false
        type: string
      macos:
        default: macos-15
        required: false
        type: string
  
jobs:
  test-ios:
    runs-on: ${{ inputs.macos }}
    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/.github/DangerFiles/Gemfile
    steps:
      - uses: actions/checkout@v4
        # We need a sufficient depth or Danger will occasionally run into issues 
        # checking which files were modified.
        with:
          fetch-depth: 100
          ref: ${{ github.head_ref }}
      - name: Install Dependencies
        env: 
          TEST_CREDENTIALS: ${{ secrets.TEST_CREDENTIALS }}
        run: |
          npm install shelljs@0.8.5
          ./install.sh
          echo $TEST_CREDENTIALS > ./shared/test/test_credentials.json
      - uses: mxcl/xcodebuild@v3
        with:
          xcode: ${{ inputs.xcode }}
          platform: iOS
          platform-version: ${{ inputs.ios }}
          workspace: SalesforceMobileSDK.xcworkspace
          scheme: ${{ inputs.lib }}
          code-coverage: true
          upload-logs: always
          verbosity: xcbeautify
      - uses: slidoapp/xcresulttool@v3.1.0
        with:
          path: test.xcresult
        if: success() || failure()
      - uses: codecov/codecov-action@v4
        with:
          flags: ${{ inputs.lib }}
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        if: success() || failure()